### ISSUE TITLE
Test failed when function call with bytes.

### ISSUE THREAD

**Issue by hackfisher** [ATNIO/atn-contracts#1]
```
Trying out/ATNTest, out/ERC223ReceivingContractTest...
.....F.

/Users/denny/github.com/dapphub/dapp/libexec/dapp/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
              ^

Error: Number can only safely store up to 53 bits
    at assert (/Users/denny/github.com/dapphub/dapp/libexec/dapp/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/denny/github.com/dapphub/dapp/libexec/dapp/node_modules/bn.js/lib/bn.js:506:7)
    at decodeSingle (/Users/denny/github.com/dapphub/dapp/libexec/dapp/node_modules/ethereumjs-abi/lib/index.js:250:54)
    at Function.ABI.rawDecode (/Users/denny/github.com/dapphub/dapp/libexec/dapp/node_modules/ethereumjs-abi/lib/index.js:367:14)
    at formatMethodCall (/Users/denny/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:277:44)
    at formatTrace (/Users/denny/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:292:152)
    at Array.forEach (<anonymous>)
    at failedTest.results.forEach.x (/Users/denny/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:214:43)
    at Array.forEach (<anonymous>)
    at printFailure (/Users/denny/github.com/dapphub/dapp/libexec/dapp/dapp-quicktest:214:22)
```

**Comment by hackfisher** [comment]
https://github.com/ATNIO/atn-contracts/blob/master/src/ATN.sol#L76
